/**
 * Moves the site's shipped content into the CMS — every photograph, and every
 * line of copy that has a field.
 *
 *   npm run seed
 *
 * Afterwards /admin is the site. lib/content.ts and lib/pages stay in the
 * repository as the FALLBACK — what the pages render on a fresh database, or
 * on any request where the database cannot be read (lib/cms/read.ts) — and
 * nothing else. Editing them no longer changes a page that has been seeded.
 *
 * WHAT IT WRITES
 *   media       every photograph the pages ship with, uploaded once
 *   home        the landing page, section by section
 *   pages       all fifteen standing-page globals
 *   projects    one document per address in the shipped rail
 *   posts       the shipped articles, published
 *
 * The photograph mapping is not written out here — it is read off the shipped
 * content. Wherever lib/content.ts or lib/pages uses a file, the field that
 * overrides that spot is filled with the upload of the same file.
 *
 * SAFE TO RE-RUN, AND IT NEVER OVERWRITES AN EDITOR. An upload is found again
 * by its filename rather than sent twice; a project or article that exists is
 * matched by its slug; and a field that already holds something is left alone.
 * "Holds something" is judged deeply — a group whose every input is still
 * blank counts as empty and is filled, a group with one line typed into it is
 * left exactly as it is. So this is also the way to top up a global after new
 * fields are added to it, which is what it was run for when the spread, the
 * practice, the ventures, Vihaa and the responsibility ledger got their copy
 * fields.
 *
 * NORMALISED ON THE WAY IN. EXIF rotation is applied (team/ram.JPG is stored
 * on its side), the long edge is capped at 2560px, opaque images are encoded as
 * JPEG and cut-outs keep their transparency as PNG. Cloudinary then serves each
 * browser its own format and quality.
 *
 * PLACEHOLDER ART IS NOT UPLOADED where a field is optional: an empty field in
 * /admin is the signal that a real photograph is still owed. An article cannot
 * be saved without a photograph, so an article whose shipped card is a
 * placeholder gets one named `placeholder-…`, easy to find and replace.
 *
 * Runs outside Next, like generate:types (see that script for why it is not
 * the Payload CLI). Revalidation is skipped on every write, so restart
 * `next dev` — or wait out the 60-second timer — to see the result.
 */

import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { getPayload, type GlobalSlug, type Payload } from "payload";
import sharp from "sharp";

import config from "../payload.config";
import {
  siteContent,
  type Cta,
  type ImageAsset,
  type SeoContent,
  type SwashHeading,
} from "../lib/content";
import {
  aboutPage,
  awardsPage,
  blogPage,
  blogPosts,
  careersPage,
  contactPage,
  disclaimerPage,
  experiencesPage,
  grievancePage,
  hospitalityPage,
  investorsPage,
  nriPage,
  pressPage,
  projectsPage,
  sustainabilityPage,
  termsPage,
  type CardItem,
  type FaqItem,
  type LedgerEntry,
  type PageHeroContent,
  type ProseClause,
  type ProseDoc,
  type Stat,
} from "../lib/pages";

const IMAGES = path.resolve(import.meta.dirname, "../public/images");
const LONG_EDGE = 2560;
/**
 * A FRESH context object per call — never one shared object.
 *
 * Payload passes this straight through to `req.context` BY REFERENCE when the
 * local API is called without a `req` (createLocalReq → getRequestContext), so
 * anything a hook writes onto it outlives the call that made it. The cloud
 * storage plugin writes two such keys: `_payloadCloudStorage`, and
 * `skipCloudStorage`, which it sets around its own nested `payload.update` and
 * then deletes from the WRONG object — that nested call replaced `req.context`
 * with a copy, so the delete never reaches the caller's.
 *
 * Share one object across calls and the leftover `skipCloudStorage: true` makes
 * the plugin's afterChange hook return early for the rest of the process: every
 * upload after the first is skipped in silence, the Media row is still written
 * with a Cloudinary URL, and nothing ever reaches Cloudinary. That is exactly
 * what the 17 September seed did — 1 of 28 files uploaded, success reported.
 * scripts/repair-cloudinary.mts cleans up after it.
 */
const context = () => ({ disableRevalidate: true });

/* ------------------------------------------------------------- the files */

/** Generated by scripts/make-placeholders.mjs: navy plates, not photographs. */
const PLACEHOLDERS = new Set([
  "concept.jpg",
  "projects/bkc-32.jpg",
  "projects/parijat.jpg",
  "projects/residency.jpg",
  "projects/royale.jpg",
]);

/** Paths the shipped content uses for a file that lives elsewhere. */
const ALIASES: Record<string, string> = {
  "hero/bkc-28.png": "projects/bkc-28.jpg",
  "projects/godrej-skygarden.jpg": "jv/skygardens.png",
};

/**
 * An upload carries one alt text wherever it is used. By default it is the alt
 * of the first place the file is met, in the order below (Home first); these
 * are the files whose shipped alts disagree, or have none.
 */
const ALT: Record<string, string> = {
  // Journey sets the hero as decoration (alt=""), but a Media document needs
  // one; this describes what the pins are placed on.
  "mainheroimage.png":
    "A rooftop terrace at dusk: an open pavilion, lounge seating and loungers along an infinity pool, with the lit city beyond the parapet",
  "jv/skygardens.png":
    "Godrej Skygarden in Badlapur at blue hour: a white residential cluster lit floor by floor above planted grounds and a lit road",
  // One photograph behind two project cards and a showcase frame, so it names
  // none of them.
  "projects/bkc-28.jpg":
    "A slender Vakratunda residential tower in Bandra at dusk, lit floor by floor above a glazed podium and the road at its foot",
  "maps.png":
    "Map of the Mumbai metropolitan region, from Mira Bhayandar south to the island city and east through Thane to Badlapur",
};

/** Flat colour and fine type: JPEG would smear the map's lettering. */
const KEEP_PNG = new Set(["maps.png"]);

/**
 * The site-wide share card. It was the last image on the site still read from
 * the repository rather than from an upload: every page that sets no card of
 * its own now falls back to the Home global's, which is this, uploaded once.
 */
const SHARE_CARD: ImageAsset = {
  src: "/images/og.jpg",
  alt: "Vakratunda Group — where dreams find an address",
  width: 1200,
  height: 630,
};

/* ------------------------------------------------------------- uploading */

const uploaded = new Map<string, number>();
const report = {
  uploaded: [] as string[],
  reused: [] as string[],
  placeholders: new Set<string>(),
  missing: new Set<string>(),
};

function fileOf(src: string): string {
  const file = src.replace(/^\/images\//, "");
  return ALIASES[file] ?? file;
}

async function upload(
  payload: Payload,
  file: string,
  alt: string,
  name?: string,
): Promise<number> {
  const input = await readFile(path.join(IMAGES, file));
  const [meta, stats] = await Promise.all([
    sharp(input).metadata(),
    sharp(input).stats(),
  ]);
  const png = KEEP_PNG.has(file) || (Boolean(meta.hasAlpha) && !stats.isOpaque);
  const base = name ?? path.basename(file).replace(/\.[^.]+$/, "").toLowerCase();
  const filename = `${base}.${png ? "png" : "jpg"}`;

  const existing = await payload.find({
    collection: "media",
    where: { filename: { equals: filename } },
    limit: 1,
    depth: 0,
  });
  if (existing.docs[0]) {
    report.reused.push(filename);
    return existing.docs[0].id;
  }

  const resized = sharp(input).rotate().resize({
    width: LONG_EDGE,
    height: LONG_EDGE,
    fit: "inside",
    withoutEnlargement: true,
  });
  const data = png
    ? await resized.png({ compressionLevel: 9 }).toBuffer()
    : await resized.jpeg({ quality: 86, mozjpeg: true }).toBuffer();

  const doc = await payload.create({
    collection: "media",
    data: { alt },
    file: {
      data,
      mimetype: png ? "image/png" : "image/jpeg",
      name: filename,
      size: data.length,
    },
    context: context(),
  });
  report.uploaded.push(`${filename} (${(data.length / 1048576).toFixed(1)} MB)`);
  return doc.id;
}

/** The upload standing in for a shipped image, or undefined where there is none to give. */
async function media(
  payload: Payload,
  asset: ImageAsset | undefined,
): Promise<number | undefined> {
  if (!asset?.src) return undefined;
  const file = fileOf(asset.src);
  if (PLACEHOLDERS.has(file)) {
    report.placeholders.add(file);
    return undefined;
  }
  if (!existsSync(path.join(IMAGES, file))) {
    report.missing.add(file);
    return undefined;
  }
  if (!uploaded.has(file)) {
    uploaded.set(file, await upload(payload, file, ALT[file] ?? asset.alt));
  }
  return uploaded.get(file);
}

/* --------------------------------------------------------------- filling */

type Json = Record<string, unknown>;

/**
 * Whether a spot in a global is still untouched.
 *
 * DEEP, and that is what lets a whole section be seeded in one entry. Payload
 * returns an unfilled group as an object of nulls and empty arrays rather than
 * as nothing at all, so a shallow check would call every group "already
 * filled" and this script would never write a word. A group is empty when
 * everything in it is; one line typed into it makes the whole group somebody's
 * work, and it is left alone.
 *
 * A boolean is never empty — `false` is an answer. That is why the SEO tab is
 * seeded field by field: `noIndex` defaults to `false` and would otherwise
 * hold the whole tab open.
 */
function isEmpty(value: unknown): boolean {
  if (value === null || value === undefined) return true;
  if (typeof value === "string") return value.trim() === "";
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === "object") return Object.values(value).every(isEmpty);
  return false;
}

/** Sets `value` at a dotted path, unless the path already holds something. */
function fill(doc: Json, dotted: string, value: unknown): boolean {
  if (isEmpty(value)) return false;
  const keys = dotted.split(".");
  let node = doc;
  for (const key of keys.slice(0, -1)) {
    if (typeof node[key] !== "object" || node[key] === null) node[key] = {};
    node = node[key] as Json;
  }
  const last = keys[keys.length - 1]!;
  if (!isEmpty(node[last])) return false;
  node[last] = value;
  return true;
}

/**
 * Fills the empty spots in a global. The whole document is read at depth 0
 * and written back, so every field this script does not touch is saved as it
 * was.
 */
async function fillGlobal(
  payload: Payload,
  slug: GlobalSlug,
  entries: [string, unknown][],
): Promise<void> {
  const data = {
    ...((await payload.findGlobal({ slug, depth: 0 })) as unknown as Json),
  };
  const filled = entries
    .filter(([dotted, value]) => fill(data, dotted, value))
    .map(([dotted]) => dotted);
  if (filled.length === 0) {
    console.log(`  ${slug}: nothing empty to fill`);
    return;
  }
  for (const key of ["id", "createdAt", "updatedAt", "globalType"]) {
    delete data[key];
  }
  await payload.updateGlobal({ slug, data: data as never, depth: 0, context: context() });
  console.log(`  ${slug}: ${filled.length} filled — ${filled.join(", ")}`);
}

/** A list of rows, dropping any whose photograph there is none to give for. */
async function rowsOf<T>(
  items: T[],
  row: (item: T) => Promise<Json | undefined>,
): Promise<Json[]> {
  const out: Json[] = [];
  for (const item of items) {
    const value = await row(item);
    if (value) out.push(value);
  }
  return out;
}

/* ------------------------------------------------------------ converters
   One per builder in fields/pageFields.ts, turning a shipped shape into the
   rows Payload stores it as. Each is the inverse of the matching merge in
   lib/cms/shapes.ts, so what goes in comes back out unchanged — which is the
   property that makes seeding invisible on the page. */

/** A repeatable plain-text field: ["a", "b"] → [{ text: "a" }, { text: "b" }]. */
const linesOf = (values: string[] | undefined): Json[] =>
  (values ?? []).map((text) => ({ text }));

/** The three-part headline. */
const swashOf = (h: SwashHeading): Json => ({
  before: h.before ?? null,
  swash: h.swash,
  after: h.after ?? null,
});

const ctaOf = (cta: Cta | undefined): Json | undefined =>
  cta ? { label: cta.label, href: cta.href } : undefined;

const heroOf = (hero: PageHeroContent): Json => ({
  label: hero.label,
  heading: swashOf(hero.heading),
  standfirst: hero.standfirst,
  meta: linesOf(hero.meta),
});

const cardsOf = (items: CardItem[]): Json[] =>
  items.map((item) => ({
    icon: item.icon ?? null,
    eyebrow: item.eyebrow ?? null,
    title: item.title,
    body: item.body,
  }));

const entriesOf = (entries: LedgerEntry[]): Json[] =>
  entries.map((entry) => ({
    meta: entry.meta,
    title: entry.title,
    note: entry.note ?? null,
    href: entry.href ?? null,
    action: entry.action ?? null,
    state: entry.state ?? null,
  }));

const statsOf = (stats: Stat[]): Json[] =>
  stats.map((stat) => ({
    value: stat.value,
    suffix: stat.suffix ?? null,
    unit: stat.unit ?? null,
    note: stat.note,
  }));

const faqsOf = (items: FaqItem[]): Json[] =>
  items.map((item) => ({
    question: item.question,
    answer: linesOf(item.answer),
  }));

const clausesOf = (clauses: ProseClause[]): Json[] =>
  clauses.map((clause) => ({
    heading: clause.heading,
    body: linesOf(clause.body),
    list: linesOf(clause.list),
  }));

/** A section head + its cards, as `cardSection()` stores them. */
const cardSectionOf = (section: {
  label?: string;
  heading: SwashHeading;
  standfirst?: string;
  lead?: string;
  items: CardItem[];
}): Json => ({
  ...(section.label === undefined ? {} : { label: section.label }),
  heading: swashOf(section.heading),
  ...(section.lead === undefined
    ? { standfirst: section.standfirst }
    : { lead: section.lead }),
  items: cardsOf(section.items),
});

/** A section head + its rows, as `ledgerSection()` stores them. */
const ledgerSectionOf = (band: {
  label?: string;
  heading: SwashHeading;
  standfirst: string;
  entries: LedgerEntry[];
  note?: string;
}): Json => ({
  ...(band.label === undefined ? {} : { label: band.label }),
  heading: swashOf(band.heading),
  standfirst: band.standfirst,
  entries: entriesOf(band.entries),
  ...(band.note === undefined ? {} : { note: band.note }),
});

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** "12 August 2025" → midnight that day in Mumbai, which is how the site reads it back. */
function istMidnight(value: string): string {
  const [day, month, year] = value.split(" ");
  const utc = Date.UTC(Number(year), MONTHS.indexOf(month!), Number(day));
  return new Date(utc - 5.5 * 60 * 60 * 1000).toISOString();
}

const docOf = (doc: ProseDoc): Json => ({
  updated: istMidnight(doc.updated),
  intro: linesOf(doc.intro),
  clauses: clausesOf(doc.clauses),
  closing: doc.closing ?? null,
  cta: ctaOf(doc.cta) ?? null,
});

/** The SEO tab, field by field — see the note in `isEmpty` about `noIndex`. */
const seoEntries = (seo: SeoContent): [string, unknown][] => [
  ["seo.title", seo.title],
  ["seo.description", seo.description],
];

/* ------------------------------------------------------------- seed: home */

async function seedHome(payload: Payload) {
  const site = siteContent;
  const m = (asset: ImageAsset | undefined) => media(payload, asset);
  const [garden, lounge, roof] = site.practice.slides;
  const { plates } = site.atmosphere;

  /** One partnership, as the three prefixed blocks on the Ventures tab. */
  const venture = async (id: string): Promise<[string, unknown][]> => {
    const slide = site.ventures.slides.find((s) => s.id === id)!;
    return [
      [`ventures.${id}`, await m(slide.image)],
      [`ventures.${id}Partner`, slide.partner],
      [`ventures.${id}Kicker`, slide.kicker],
      [`ventures.${id}Stat1Label`, slide.stats[0].label],
      [`ventures.${id}Stat1Value`, slide.stats[0].value],
      [`ventures.${id}Stat2Label`, slide.stats[1].label],
      [`ventures.${id}Stat2Value`, slide.stats[1].value],
      [`ventures.${id}Blurb`, slide.blurb],
      [`ventures.${id}CtaLabel`, slide.cta.label],
      [`ventures.${id}CtaHref`, slide.cta.href],
    ];
  };

  await fillGlobal(payload, "home", [
    /* ---- Navigation ---- */
    ["nav.links", site.nav.links.map((l) => ({ label: l.label, href: l.href }))],
    ["nav.ctaLabel", site.nav.cta.label],
    ["nav.ctaHref", site.nav.cta.href],

    /* ---- Hero ---- */
    ["hero.heading", swashOf(site.hero.heading)],
    ["hero.standfirst", site.hero.standfirst],
    ["hero.meta", linesOf(site.hero.meta)],
    ["hero.ctaLabel", site.hero.primaryCta.label],
    ["hero.ctaHref", site.hero.primaryCta.href],
    ["hero.scrollCue", site.hero.scrollCue],
    ["hero.background", await m(site.hero.background)],
    [
      "hero.pins",
      site.hero.pins.map((pin) => ({
        title: pin.title,
        x: pin.x,
        y: pin.y,
        body: linesOf(pin.body),
        evidence: pin.evidence,
        ctaLabel: pin.cta.label,
        ctaHref: pin.cta.href,
      })),
    ],

    /* ---- Impact ---- */
    ["immersive.heading", swashOf(site.immersive.heading)],
    ["immersive.standfirst", site.immersive.standfirst],
    [
      "immersive.hotspots",
      site.immersive.hotspots.map((spot) => ({
        value: spot.value,
        unit: spot.unit ?? null,
        x: spot.x,
        y: spot.y,
        title: spot.title,
        body: spot.body,
      })),
    ],

    /* ---- Story ---- */
    ["concept.lockup.wordmark", site.concept.lockup.wordmark],
    ["concept.lockup.caption", linesOf(site.concept.lockup.caption)],
    ["concept.arcText", site.concept.arcText],
    ["concept.body", linesOf(site.concept.body)],
    ["concept.legacy.kicker", site.concept.legacy.kicker],
    ["concept.legacy.heading", swashOf(site.concept.legacy.heading)],
    ["concept.legacy.body", site.concept.legacy.body],
    [
      "concept.legacy.proofs",
      site.concept.legacy.proofs.map((proof) => ({
        icon: proof.icon,
        value: proof.value ?? null,
        suffix: proof.suffix ?? null,
        unit: proof.unit ?? null,
        phrase: proof.phrase ?? null,
        note: proof.note,
      })),
    ],
    ["concept.legacyImage", await m(site.concept.legacy.image)],
    ["concept.showcaseHeading", swashOf(site.concept.showcase.heading)],
    [
      "concept.showcase",
      await rowsOf(site.concept.showcase.slides, async (slide) => {
        const image = await m(slide.image);
        return image === undefined
          ? undefined
          : { name: slide.name, caption: slide.caption, image };
      }),
    ],

    /* ---- Projects ---- */
    ["gallery.heading", swashOf(site.gallery.heading)],
    ["gallery.standfirst", site.gallery.standfirst],
    ["gallery.map", await m(site.gallery.map)],
    ["gallery.ctaLabel", site.gallery.cta.label],
    ["gallery.ctaHref", site.gallery.cta.href],

    /* ---- Spread ---- */
    ["atmosphere.eyebrow", site.atmosphere.eyebrow],
    ["atmosphere.heading", swashOf(site.atmosphere.heading)],
    ["atmosphere.lead", site.atmosphere.lead],
    ["atmosphere.deck", await m(plates.deck.image)],
    ["atmosphere.deckSide", plates.deck.side],
    ["atmosphere.deckNote", plates.deck.note],
    ["atmosphere.glass", await m(plates.glass.image)],
    ["atmosphere.glassSide", plates.glass.side],
    ["atmosphere.glassNote", plates.glass.note],
    ["atmosphere.terrace", await m(plates.terrace.image)],
    ["atmosphere.terraceSide", plates.terrace.side],
    ["atmosphere.terraceNote", plates.terrace.note],
    ["atmosphere.lounge", await m(plates.lounge.image)],
    ["atmosphere.loungeSide", plates.lounge.side],
    ["atmosphere.garden", await m(plates.garden.image)],
    ["atmosphere.gardenSide", plates.garden.side],
    ["atmosphere.gardenNote", plates.garden.note],
    ["atmosphere.detailsTitle", site.atmosphere.detailsTitle],
    ["atmosphere.details", linesOf(site.atmosphere.details)],
    ["atmosphere.coda", site.atmosphere.coda],

    /* ---- Practice ---- */
    ["practice.statement", swashOf(site.practice.statement)],
    ["practice.detail", site.practice.detail],
    ["practice.ctaLabel", site.practice.cta.label],
    ["practice.ctaHref", site.practice.cta.href],
    ["practice.commitmentsTitle", site.practice.commitmentsTitle],
    ["practice.commitments", linesOf(site.practice.commitments)],
    ["practice.wide", await m(site.practice.wide)],
    ["practice.portrait", await m(site.practice.portrait)],
    [
      "practice.garden",
      { image: await m(garden?.image), place: garden?.place, caption: garden?.caption },
    ],
    [
      "practice.lounge",
      { image: await m(lounge?.image), place: lounge?.place, caption: lounge?.caption },
    ],
    [
      "practice.roof",
      { image: await m(roof?.image), place: roof?.place, caption: roof?.caption },
    ],

    /* ---- Team ---- */
    ["team.heading", swashOf(site.team.heading)],
    ["team.standfirst", site.team.standfirst],
    ["team.interstitial.heading", swashOf(site.team.interstitial.heading)],
    ["team.interstitial.subtext", site.team.interstitial.subtext],
    ["team.intro.image", await m(site.team.intro.image)],
    ["team.intro.ctaLabel", site.team.intro.ctaLabel],
    ["team.chairman.name", site.team.chairman.name],
    ["team.chairman.title", site.team.chairman.title],
    ["team.chairman.quote", swashOf(site.team.chairman.quote)],
    ["team.chairman.superpower", site.team.chairman.superpower],
    ["team.chairman.bio", site.team.chairman.bio],
    ["team.chairman.portrait", await m(site.team.chairman.portrait)],
    ["team.chairman.ctaLabel", site.team.chairman.ctaLabel],
    [
      "team.leadership",
      await rowsOf(site.team.leadership, async (member) => ({
        name: member.name,
        title: member.title,
        superpower: member.superpower,
        bio: member.bio,
        portrait: await m(member.portrait),
      })),
    ],
    [
      "team.roles",
      site.team.roles.map((role) => ({
        title: role.title,
        icon: role.icon,
        descriptor: role.descriptor,
      })),
    ],
    ["team.roleCtaLabel", site.team.roleCta.label],
    ["team.roleCtaHref", site.team.roleCta.href],
    ["team.bioCtaLabel", site.team.bioCtaLabel],

    /* ---- Ventures ---- */
    ["ventures.heading", swashOf(site.ventures.heading)],
    ["ventures.standfirst", site.ventures.standfirst],
    ...(await venture("godrej")),
    ...(await venture("shapoorji")),
    ...(await venture("redevelopment")),

    /* ---- Vihaa ---- */
    ["vihaa.nameMark", site.vihaa.name.mark],
    ["vihaa.nameRest", site.vihaa.name.rest],
    ["vihaa.heading", swashOf(site.vihaa.heading)],
    ["vihaa.standfirst", site.vihaa.standfirst],
    ["vihaa.fact1Label", site.vihaa.facts[0].label],
    ["vihaa.fact1Value", site.vihaa.facts[0].value],
    ["vihaa.fact2Label", site.vihaa.facts[1].label],
    ["vihaa.fact2Value", site.vihaa.facts[1].value],
    ["vihaa.note", site.vihaa.note],
    ["vihaa.cover", await m(site.vihaa.cover)],
    [
      "vihaa.moments",
      await rowsOf(site.vihaa.moments, async (moment) => {
        const image = await m(moment);
        return image === undefined
          ? undefined
          : { image, caption: moment.caption };
      }),
    ],

    /* ---- Responsibility ---- */
    ["responsibility.heading", swashOf(site.responsibility.heading)],
    ["responsibility.standfirst", site.responsibility.standfirst],
    ["responsibility.image", await m(site.responsibility.image)],
    ["responsibility.imageCaption", site.responsibility.image.caption],
    ["responsibility.environment.label", site.responsibility.environment.label],
    ["responsibility.environment.lead", site.responsibility.environment.lead],
    [
      "responsibility.environment.commitments",
      site.responsibility.environment.commitments.map((c) => ({
        title: c.title,
        icon: c.icon,
        detail: c.detail,
      })),
    ],
    ["responsibility.coda", site.responsibility.coda],

    /* ---- Contact ---- */
    ["finalCta.quote", swashOf(site.finalCta.quote)],
    ["finalCta.attribution", site.finalCta.attribution],
    [
      "finalCta.proofs",
      site.finalCta.proofs.map((p) => ({ title: p.title, body: p.body })),
    ],
    ["finalCta.ctaLabel", site.finalCta.primaryCta.label],
    ["finalCta.ctaHref", site.finalCta.primaryCta.href],
    ["finalCta.email", site.finalCta.contact.email],
    ["finalCta.addressLines", linesOf(site.finalCta.contact.addressLines)],
    ["legal", site.legal],

    ...seoEntries(site.seo),
    ["seo.image", await m(SHARE_CARD)],
  ]);
}

/* ------------------------------------------------------- seed: the pages */

async function seedPages(payload: Payload) {
  const m = (asset: ImageAsset | undefined) => media(payload, asset);

  await fillGlobal(payload, "about-page", [
    ["hero", heroOf(aboutPage.hero)],
    [
      "story",
      {
        label: aboutPage.story.label,
        heading: swashOf(aboutPage.story.heading),
        standfirst: aboutPage.story.standfirst,
        body: linesOf(aboutPage.story.body),
        image: await m(aboutPage.story.image),
        imageCaption: aboutPage.story.image.caption ?? null,
        pullquote: aboutPage.story.pullquote,
      },
    ],
    ["principles", cardSectionOf(aboutPage.principles)],
    ...seoEntries(aboutPage.seo),
  ]);

  await fillGlobal(payload, "projects-page", [
    ["hero", heroOf(projectsPage.hero)],
    ["filterLabel", projectsPage.filterLabel],
    ["allLabel", projectsPage.allLabel],
    ["emptyMessage", projectsPage.emptyMessage],
    ["note", projectsPage.note],
    ...seoEntries(projectsPage.seo),
  ]);

  await fillGlobal(payload, "sustainability-page", [
    ["hero", heroOf(sustainabilityPage.hero)],
    ["environment", cardSectionOf(sustainabilityPage.environment)],
    ["coda", sustainabilityPage.coda],
    ["cta", ctaOf(sustainabilityPage.cta)],
    ...seoEntries(sustainabilityPage.seo),
  ]);

  await fillGlobal(payload, "experiences-page", [
    ["hero", heroOf(experiencesPage.hero)],
    [
      "day",
      {
        ...cardSectionOf(experiencesPage.day),
        figures: await rowsOf(experiencesPage.day.figures, async (figure) => {
          const image = await m(figure);
          return image === undefined
            ? undefined
            : { image, caption: figure.caption ?? null };
        }),
      },
    ],
    ["standard", cardSectionOf(experiencesPage.standard)],
    ["coda", experiencesPage.coda],
    ["cta", ctaOf(experiencesPage.cta)],
    ...seoEntries(experiencesPage.seo),
  ]);

  await fillGlobal(payload, "hospitality-page", [
    ["hero", heroOf(hospitalityPage.hero)],
    [
      "story",
      {
        label: hospitalityPage.story.label,
        heading: swashOf(hospitalityPage.story.heading),
        standfirst: hospitalityPage.story.standfirst,
        body: linesOf(hospitalityPage.story.body),
        image: await m(hospitalityPage.story.image),
        imageCaption: hospitalityPage.story.image.caption ?? null,
        pullquote: hospitalityPage.story.pullquote,
      },
    ],
    ["offer", cardSectionOf(hospitalityPage.offer)],
    ["stats", statsOf(hospitalityPage.stats)],
    ["coda", hospitalityPage.coda],
    ["cta", ctaOf(hospitalityPage.cta)],
    ...seoEntries(hospitalityPage.seo),
  ]);

  await fillGlobal(payload, "nri-page", [
    ["hero", heroOf(nriPage.hero)],
    ["steps", cardSectionOf(nriPage.steps)],
    [
      "faqs",
      {
        label: nriPage.faqs.label,
        heading: swashOf(nriPage.faqs.heading),
        standfirst: nriPage.faqs.standfirst,
        items: faqsOf(nriPage.faqs.items),
      },
    ],
    ["disclaimer", nriPage.disclaimer],
    ["cta", ctaOf(nriPage.cta)],
    ...seoEntries(nriPage.seo),
  ]);

  await fillGlobal(payload, "investors-page", [
    ["hero", heroOf(investorsPage.hero)],
    ["statsLabel", investorsPage.statsLabel],
    ["stats", statsOf(investorsPage.stats)],
    ["governance", cardSectionOf(investorsPage.governance)],
    ["documents", ledgerSectionOf(investorsPage.documents)],
    ["coda", investorsPage.coda],
    ["cta", ctaOf(investorsPage.cta)],
    ...seoEntries(investorsPage.seo),
  ]);

  await fillGlobal(payload, "press-page", [
    ["hero", heroOf(pressPage.hero)],
    ["coverage", ledgerSectionOf(pressPage.coverage)],
    ["enquiries", ledgerSectionOf(pressPage.enquiries)],
    ...seoEntries(pressPage.seo),
  ]);

  await fillGlobal(payload, "awards-page", [
    ["hero", heroOf(awardsPage.hero)],
    ["awards", ledgerSectionOf(awardsPage.awards)],
    ["certifications", cardSectionOf(awardsPage.certifications)],
    ["coda", awardsPage.coda],
    ...seoEntries(awardsPage.seo),
  ]);

  await fillGlobal(payload, "blog-page", [
    ["hero", heroOf(blogPage.hero)],
    [
      "listing",
      {
        label: blogPage.listing.label,
        heading: swashOf(blogPage.listing.heading),
        standfirst: blogPage.listing.standfirst,
      },
    ],
    ["note", blogPage.note],
    [
      "article",
      {
        contentsLabel: blogPage.article.contentsLabel,
        updatedLabel: blogPage.article.updatedLabel,
        byline: linesOf(blogPage.article.byline),
        backCta: ctaOf(blogPage.article.backCta),
      },
    ],
    ...seoEntries(blogPage.seo),
  ]);

  await fillGlobal(payload, "careers-page", [
    ["hero", heroOf(careersPage.hero)],
    ["culture", cardSectionOf(careersPage.culture)],
    ["stats", statsOf(careersPage.stats)],
    ["roles", ledgerSectionOf(careersPage.roles)],
    ["process", cardSectionOf(careersPage.process)],
    ...seoEntries(careersPage.seo),
  ]);

  await fillGlobal(payload, "contact-page", [
    ["hero", heroOf(contactPage.hero)],
    ["channels", ledgerSectionOf(contactPage.channels)],
    [
      "form",
      {
        label: contactPage.form.label,
        heading: contactPage.form.heading,
        standfirst: contactPage.form.standfirst,
        note: contactPage.form.note,
      },
    ],
    [
      "office",
      {
        label: contactPage.office.label,
        heading: swashOf(contactPage.office.heading),
        standfirst: contactPage.office.standfirst,
        addressLines: linesOf(contactPage.office.addressLines),
        hours: linesOf(contactPage.office.hours),
        image: await m(contactPage.office.image),
        imageCaption: contactPage.office.image.caption ?? null,
      },
    ],
    ...seoEntries(contactPage.seo),
  ]);

  /* The three documents. ⚠️ None of them is approved by counsel — see the
     notice at the head of lib/pages/legal.ts. Seeding them changes where the
     text is edited, not whether it may be published. */
  for (const [slug, page] of [
    ["terms-page", termsPage],
    ["disclaimer-page", disclaimerPage],
    ["grievance-page", grievancePage],
  ] as const) {
    await fillGlobal(payload, slug, [
      ["hero", heroOf(page.hero)],
      ["doc", docOf(page.doc)],
      ...seoEntries(page.seo),
    ]);
  }
}

/**
 * The home-page rail. Created in the shipped order, so a card left without a
 * photograph still falls back to the shipped card in the same position.
 */
async function seedProjects(payload: Payload) {
  for (const [index, slide] of siteContent.gallery.slides.entries()) {
    const cardImage = await media(payload, slide.image);
    const { docs } = await payload.find({
      collection: "projects",
      where: { slug: { equals: slide.id } },
      limit: 1,
      depth: 0,
    });
    const existing = docs[0];

    if (!existing) {
      await payload.create({
        collection: "projects",
        data: {
          name: slide.name,
          locality: slide.locality,
          status: slide.status,
          order: index + 1,
          slug: slide.id,
          blurb: slide.blurb,
          cardImage,
        },
        context: context(),
      });
      console.log(
        `  projects/${slide.id}: created${cardImage === undefined ? " (no card image)" : ""}`,
      );
    } else if (!existing.cardImage && cardImage !== undefined) {
      await payload.update({
        collection: "projects",
        id: existing.id,
        data: { cardImage },
        context: context(),
      });
      console.log(`  projects/${slide.id}: card image filled`);
    }
  }
}

/**
 * The shipped articles. Publishing the first one makes the collection the
 * only source for /blogs (lib/getBlogPosts.ts), so all of them go in together.
 */
async function seedPosts(payload: Payload) {
  for (const post of blogPosts) {
    const { totalDocs } = await payload.count({
      collection: "posts",
      where: { slug: { equals: post.slug } },
    });
    if (totalDocs > 0) continue;

    const image =
      (await media(payload, post.image)) ??
      (await upload(
        payload,
        fileOf(post.image.src),
        post.image.alt,
        `placeholder-${post.slug}`,
      ));

    await payload.create({
      collection: "posts",
      draft: false,
      data: {
        title: post.title,
        slug: post.slug,
        swashTitle: post.swashTitle,
        category: post.category,
        readingTime: post.readingTime,
        publishedAt: istMidnight(post.date),
        excerpt: post.excerpt,
        image,
        sections: post.body.map((clause) => ({
          heading: clause.heading,
          body: clause.body?.map((text) => ({ text })),
          list: clause.list?.map((text) => ({ text })),
        })),
        _status: "published",
      },
      context: context(),
    });
    console.log(`  posts/${post.slug}: published`);
  }
}

/* ------------------------------------------------------------------- run */

const payload = await getPayload({ config: await config });

console.log("Home");
await seedHome(payload);
console.log("Pages");
await seedPages(payload);
console.log("Projects");
await seedProjects(payload);
console.log("Articles");
await seedPosts(payload);

console.log(`\nUploaded ${report.uploaded.length}:`);
for (const line of report.uploaded) console.log(`  ${line}`);
if (report.reused.length > 0) {
  console.log(`Already in the library: ${report.reused.join(", ")}`);
}
if (report.placeholders.size > 0) {
  console.log(
    `Placeholder art, left out (fields stay empty until a photograph arrives): ${[...report.placeholders].join(", ")}`,
  );
}
if (report.missing.size > 0) {
  console.log(`Referenced but not on disk: ${[...report.missing].join(", ")}`);
}

process.exit(0);
